version: "3.1"


services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always

  postgresdb:
    build:
      context: ./dj_bot/docker/postgres
      dockerfile: Dockerfile
    environment:
      - POSTGRES_PASSWORD=$PASSWORD_DB
    volumes:
      - ./dj_bot/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: always

  web:
    build:
      context: ./dj_bot/
      dockerfile: Dockerfile
    volumes:
      - ./dj_bot/:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
          - postgresdb
    restart: always

  nginx:
    build:
      context: ./dj_bot/docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - postgresdb
    ports:
      - "80:80"
    volumes:
      - ./dj_bot/static/:/static
    restart: always

#  tg_bot:
#    build:
#      context: ./tg_bot
#      dockerfile: Dockerfile
#    volumes:
#      - ./tg_bot/:/src
#    depends_on:
#      - postgresdb
#      - web
#      - nginx
#      - redis
#    command: python app.py
#    restart: always
